language: r

dist: trusty
sudo: false
warnings_are_errors: false

env:
  matrix:
    - TF_VERSION="1.4"
    - TF_VERSION="nightly"

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - source scripts/travis_install.sh

script:
  - |
    R CMD build .
    R CMD check --no-build-vignettes --no-manual tfdeploy*tar.gz

after_failure:
  - |
    cd tests
    travis_wait 30 Rscript ../.travis.R
    sleep 2
